baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'Craft Component Library'
primary: true
siteGroup: 51654125-ba3b-4c46-a00b-0a3643243efd # Craft Component Library
sortOrder: 1
